"""Add InactiveLeadList

Revision ID: 172a5f9c3565
Revises: 2cc8ab7fdebe
Create Date: 2026-07-06 23:18:30.555686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '172a5f9c3565'
down_revision: Union[str, Sequence[str], None] = '2cc8ab7fdebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inactive_leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('tagged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inactive_leads_email'), 'inactive_leads', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inactive_leads_email'), table_name='inactive_leads')
    op.drop_table('inactive_leads')
    # ### end Alembic commands ###
