"""Init postgresql schema

Revision ID: 2cc8ab7fdebe
Revises: 
Create Date: 2026-07-06 17:42:31.688257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cc8ab7fdebe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracking_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_logs_campaign_id'), 'tracking_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_tracking_logs_contact_id'), 'tracking_logs', ['contact_id'], unique=False)
    op.create_table('unsubscribes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('unsubscribed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unsubscribes_email'), 'unsubscribes', ['email'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('verification_code', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('gemini_api_key', sa.String(), nullable=True),
    sa.Column('groq_api_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('sent_count', sa.Integer(), nullable=True),
    sa.Column('opens', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('is_ab_test', sa.Boolean(), nullable=True),
    sa.Column('subject_b', sa.String(), nullable=True),
    sa.Column('body_b', sa.Text(), nullable=True),
    sa.Column('sent_count_a', sa.Integer(), nullable=True),
    sa.Column('sent_count_b', sa.Integer(), nullable=True),
    sa.Column('opens_a', sa.Integer(), nullable=True),
    sa.Column('opens_b', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('delay_min', sa.Integer(), nullable=True),
    sa.Column('delay_max', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sending_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('smtp_server', sa.String(), nullable=False),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_username', sa.String(), nullable=False),
    sa.Column('smtp_password', sa.String(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('sent_today', sa.Integer(), nullable=True),
    sa.Column('imap_server', sa.String(), nullable=True),
    sa.Column('imap_port', sa.Integer(), nullable=True),
    sa.Column('imap_password', sa.String(), nullable=True),
    sa.Column('warmup_enabled', sa.Boolean(), nullable=True),
    sa.Column('warmup_daily_limit', sa.Integer(), nullable=True),
    sa.Column('warmup_increment_per_day', sa.Integer(), nullable=True),
    sa.Column('warmup_sent_today', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sending_accounts_email'), 'sending_accounts', ['email'], unique=True)
    op.create_table('webhooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('events', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('campaign_id', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('variant', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_leads_campaign_id'), 'campaign_leads', ['campaign_id'], unique=False)
    op.create_table('replies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('sender_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['sending_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_index(op.f('ix_campaign_leads_campaign_id'), table_name='campaign_leads')
    op.drop_table('campaign_leads')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_sending_accounts_email'), table_name='sending_accounts')
    op.drop_table('sending_accounts')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_unsubscribes_email'), table_name='unsubscribes')
    op.drop_table('unsubscribes')
    op.drop_index(op.f('ix_tracking_logs_contact_id'), table_name='tracking_logs')
    op.drop_index(op.f('ix_tracking_logs_campaign_id'), table_name='tracking_logs')
    op.drop_table('tracking_logs')
    # ### end Alembic commands ###
