"""add_health_score_to_sending_accounts

Revision ID: 7c96ed084a3c
Revises: 172a5f9c3565
Create Date: 2026-07-06 23:30:20.457835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c96ed084a3c'
down_revision: Union[str, Sequence[str], None] = '172a5f9c3565'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sending_accounts', sa.Column('health_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sending_accounts', 'health_score')
    # ### end Alembic commands ###
